org: yuriitsekhovyi
app: text-extractor
service: text-extractor

frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'
  fileTableName: 'files-table-${sls:stage}'
  bucketName: text-extractor-bucket
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - textract:StartDocumentTextDetection
            - textract:GetDocumentTextDetectionStatus
            - textract:GetDocumentTextDetectionResult
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
            - Fn::GetAtt: [ FilesTable, Arn ]
            - arn:aws:s3:::${self:custom.bucketName}
            - arn:aws:textract:::job/*


  environment:
    USERS_TABLE: ${self:custom.tableName}
    FILES_TABLE: ${self:custom.fileTableName}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
    FilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: fileId
            AttributeType: S
        KeySchema:
          - AttributeName: fileId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.fileTableName}
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
